### ISSUE TITLE
Docker hub repo -Which one is really official ?

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Docker.Official.Image#112]
There are https://hub.docker.com/_/rocket-chat?tab=tags and https://hub.docker.com/r/rocketchat/rocket.chat/tags. Which one is official docker repo? One seems to be twice bigger than the other.

**Comment by aminvakil** [comment]
Both.

https://github.com/RocketChat/Rocket.Chat#docker

https://hub.docker.com/_/rocket-chat is a release approved by docker team too, therefore it will be always older (from my experience about two weeks) than the rocketchat official one.

But interesting point you've mentioned about size, I don't know either.

**Comment by jsalatiel** [comment]
@sampaiodiego  Do you know why the size is different ?

**Comment by jsalatiel** [comment]
One thing that I also have noticed is that one of the repos has a much more vulnerable image when scanned by Clair. 3.2.2 is the one approved by docker team.
![image](https://user-images.githubusercontent.com/5522389/83264996-464ff400-a197-11ea-9ba4-21ee14b0017d.png)

**Comment by sampaiodiego** [comment]
> @sampaiodiego Do you know why the size is different ?

the size difference is because they are built from very different Dockefiles ([docker official](https://github.com/RocketChat/Docker.Official.Image/blob/master/3/Dockerfile) and [rocket.chat](https://github.com/RocketChat/Rocket.Chat/blob/develop/.docker/Dockerfile)). the same applies to vulnerabilities as they depend on different base images.

we've discussed a few times if we should have only one Docker image.. the main issue is that sometimes we want to published "special images" or images used for testing purposes, in this cases the "official docker" images are not suitable for.

I'll at least try to use a more close Dockerfile for both images, it will reduce the differences (either in size and vulnerabilities) between them and also help maintainability 👍
