### ISSUE TITLE
Problems with spanish translations

### ISSUE THREAD

**Issue by antonjos** [RocketChat/Docker.Official.Image#135]
There are issues with spanishs translations, i18n.es.chunk.44d0d.js seems to have unaccurate or even english messages
This problems are detected in docker image rocketchat/rocket.chat:3.2.2

**Comment by sampaiodiego** [comment]
thanks for reporting @antonjos .. translations are mainly provided by community at this point.

contributions are more than welcome, if you have git knowledge and want to help you can modify this file on main repo: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/es.i18n.json

otherwise please check out our doc page on how to help https://docs.rocket.chat/contributors/contributing/translating

I'll be closing this issue since not related to the Docker image itself.. thx
