### ISSUE TITLE
gpg key: No name

### ISSUE THREAD

**Issue by serhi0z** [RocketChat/Docker.Official.Image#145]
$ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104
gpg: keyserver receive failed: No name

is it ok ?

**Comment by bhordupur** [comment]
I can fix it before you finish your tea/coffee

**Comment by HatBeardZero** [comment]
is there a fix for it?  i see the following on their website, and cannot resolve any of the DNS entries...

This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.
