### ISSUE TITLE
Error tar: "Directory renamed before its status could be extracted"

### ISSUE THREAD

**Issue by Jonathanyyf** [RocketChat/Docker.Official.Image#55]
The dockerfile use tar which is broken in docker(?)
https://github.com/docker/hub-feedback/issues/727
```
tar: bundle/programs/server/npm/node_modules/express/node_modules/.bin: Directory renamed before its status could be extracted
tar: bundle/programs/server/npm/node_modules/express/node_modules: Directory renamed before its status could be extracted
tar: bundle/programs/server/npm/node_modules/express: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c curl -fSL "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz &&  curl -fSL "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc &&  gpg --batch --verify rocket.chat.tgz.asc rocket.chat.tgz &&  tar zxvf rocket.chat.tgz &&  rm rocket.chat.tgz rocket.chat.tgz.asc &&  cd bundle/programs/server &&  npm install' returned a non-zero code: 2
```

**Comment by L3rchal** [comment]
Same error here.

**Comment by Climbgunks** [comment]
Also seeing this problem on the latest stable version of docker on a mac (up-to-date High Sierra), basing an image off of centos:latest.      Trying to extract a very large tarball inside the container during software install generates the same error as above.   Repeatable.     I can't re-distribute the software tarball however.

Btw, replacing tar w/ bsdtar isn't really a useful solution since I don't control the software packaging...and they're not direct replacements for each other.

As noted elsewhere, aufs works, but is being deprecated

**Comment by geekgonecrazy** [comment]
I've seen this in random images when building on mac.  Don't think related to this image.

Closing
