### ISSUE TITLE
MongoError: not master and slaveOk=false

### ISSUE THREAD

**Issue by mabushey** [RocketChat/Docker.Official.Image#67]
This is #50 , which was closed w/o a fix.

Trying to use RocketChat which uses Mongo 4.0.  I've used MySQL for over 20 years and it's amazing. People also love Postgress. Redis is rock solid. I've used Mongo in production; it's total crap.

`Exception in setInterval callback: { MongoError: not master and slaveOk=false`

**Comment by sampaiodiego** [comment]
you need to configure your MongoDB as Replica Set.. you can follow this official tutorial: https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

If you want to give Rocket.Chat on a deployment **not designed for production**, you can use MongoDB without configuring it as replica set. to do that just removes the `MONGO_OPLOG_URL` env var from you startup.

I'll be closing the issue since this is not an issue with Rocket.Chat nor its Official imagem.

**Comment by achaiah** [comment]
Hi @sampaiodiego, could you please be more specific in your reply? How could I run Rocket.Chat with a single instance of MongoDB?  I have a docker-compose.yml file but it does not specify any `MONGO_OPLOG_URL` and still I get the same issue as above.

Thanks

**Comment by sampaiodiego** [comment]
hi @achaiah .. starting from version [1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/1.0.0) we have removed the possibility to run Rocket.Chat without using a replica set.

that means you'll **need** to set the `MONGO_OPLOG_URL` env var.. you can have a single MongoDB as replica set, please the tutorial I've shared before https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

**Comment by clpacheco90** [comment]
I got the same error and its occurring because rocket.chat starts first then the replicaset containers. 
So I add the command on docker-compose file:
```sh
...
    image: "rocket.chat"
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"    
...
```
https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

**Comment by AllardKrings** [comment]
Hi, I am having the same problem. 

Situation: 

I run Rocketchat with a 3-fold Mongo-replicaset: Pods named mongodb-0, mongodb-1 and  mongodb-2. . It works fine. 

But after a power interupt on the cluster Mongo-DB has changed wich member of the replicaset is the Primary.  Before the power interupt Mongo-0 is the primary, after the power interrupt Mongo-2 has become Primary.

Because the Rocketchat configuration expect mongodb-0 to be the primary:

            - name: MONGO_OPLOG_URL
               value: mongodb://**mongodb-0.**mongodb:27017/local?replSet=rs0

this results the following error in the Rocketchat logs: 

/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoError: not master and slaveOk=false
    at MessageStream.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:718:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1663192744 },
  ok: 0,
  code: 13435,
  codeName: 'NotMasterNoSlaveOk',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1663192744 },
    signature: {
      hash: Binary {
        _bsontype: 'Binary',
        sub_type: 0,
        position: 20,
        buffer: Buffer(20) [Uint8Array] [
          0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0
        ]
      },
      keyId: 0
    }
  },
  [Symbol(errorLabels)]: Set { 'RetryableWriteError' }


Does anybody know how to solve this?
